### ISSUE TITLE
라이브러리가 es2015 module로 작성돼있으면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by disjukr** [redcamel/RedGL2#403]
라이브러리가 es2015 module을 사용하여 작성되어있으면, 라이브러리를 사용하는 사람이 webpack이나 rollup 등의 js 번들러를 사용할 경우 [사용하지 않는 모듈들이 자동으로 제거되는 최적화](https://webpack.js.org/guides/tree-shaking/)를 누릴 수 있습니다.

[현재 빌드과정](https://github.com/redcamel/RedGL2/blob/ba1e2df5d298d9c7bdf907bee6ce6c108eaf4ffb/gulpfile.js#L118-L262)은 모든 스크립트를 concat하고 uglify한뒤 약간의 배너를 더하고 있는데, 빌드 속도를 위한 선택이었다면 [pax](https://github.com/nathan/pax)와 같이 매우 빠른 번들러를 사용하는 것을 고려해볼 수 있을 것 같습니다.

빌드 속도를 약간 타협할 수 있다면, 개발 빌드에서는 [sucrase](https://github.com/alangpierce/sucrase)를 uglify 없이 사용하고, 프로덕션 빌드에서는 babel이나 tsc를 webpack과 같이 사용하는 방법도 좋을 것 같습니다.

**Comment by redcamel** [comment]
@disjukr 
RedGL은 JS 5.1기준으로 작성되었습니다. 왜냐하면.. 가능한 모든 디바이스상에서 동작하기 위함입니다.
(적어도 JS떄문에 안돌아가는 사태는 없습니다.) 바벨을 이용해서 트랜스 컴파일 하면되지않는가? 라고 할수도있습니다... 동작은 하겠지만 트랜스 컴파일시 최적화 되지않은 JS코드가 양산되는게 현실이니...
5.1기반은 유지할생각입니다.

**Comment by disjukr** [comment]
pax, sucrase 등의 컴파일러는 최소한의 치환만을 사용하여 트랜스파일하기 때문에 es2015 module 문법만 더할 경우 나머지 코드에 대해서는 변형되는 바가 없습니다.

게다가 모듈 관련 코드는 js 로드시 처음 한 번만 실행될 뿐이기 때문에 성능 저하 문제에서 자유롭습니다.

---

별개로 다른 문법등을 트랜스파일시에 최적화되지 않은 코드가 발생할 수 있는 문제는.. 보통은 직접 작성하는 것보다 빠르게 작동하는 코드를 뱉기 때문에 문제가 없다고 생각합니다만

> 예를 들어 [typescript playground](https://www.typescriptlang.org/play/)에서 트랜스파일된 결과물 확인해보면, `for ... of`등의 현대 순회 문법을 사용하여 작성할 경우, array 순회라고 단정할 수 있을 때 전통적인 c 스타일 순회로 변환해주는 것을 확인할 수 있습니다.
> <img width="1243" alt="2019-01-03 11 39 34" src="https://user-images.githubusercontent.com/690661/50621885-5d5fc780-0f4c-11e9-8b04-ad17d1eb97e1.png">

코드 맹글링 단계에서 uglifyjs를 closure compiler로 교체한뒤 `ADVANCED_OPTIMIZATION` 기능을 활성화시키거나 [prepack](https://prepack.io/) 등의 공격적인 최적화 기법을 적용할 경우, 조금 더 가정할 수 있는 단서가 많은 최신 문법을 사용하는 쪽이 최적화에 더 효율적일 수 있습니다.

**Comment by disjukr** [comment]
네, 저도 기존의 코드를 일괄적으로 현대 문법으로 재작성 하였을 때 예상치 못한 곳에서 성능저하가 일어날 수 있다고는 생각합니다.

이 이슈는 기존에 작성된 모든 코드를 현대화하자는 이슈가 아니고, 현재의 모듈 구조를 es2015 module 문법을 사용하도록만 바꾸자는 것입니다.

예를 들어 기존의 코드를 수정없이 그대로 babel이나 typescript에서 es5 타겟으로 트랜스파일할 경우, 코드 들여쓰기나 공백 등을 제외하면 나머지 내용들이 그대로 출력될 것입니다.

여기에 모듈문법만을 더해서 사용할 경우 렌더링 성능에 영향을 줄 수 있는 변화는 전혀 없을거라고 생각합니다.

**Comment by redcamel** [comment]
@disjukr 그부분은 충분히 동의, 공감합니다..^^

**Comment by hikaMaeng** [comment]
그래도 하면 안됨 ^^

**Comment by hikaMaeng** [comment]
차라리 다른 기여자가 타입스크립트로 재작성하는걸 기부받으라능..
지금이 최적 모바일 호환 및 성능 및 여러 브라우저 호환상태임.

**Comment by disjukr** [comment]
@hikaMaeng 지금 모듈 코드들이 전부 전역변수를 선언한다음 iife 블럭 안에서 객체를 만들어서 대입할 뿐인데요,
es2015 module 문법을 사용해서 소스코드를 작성해놓는다면 상기한 이점을 누리면서 `release/RedGL.min.js`로 컴파일할 때는 지금 모양과 정확히 똑같은 런타임 시맨틱으로 컴파일되도록 컴파일러 플러그인을 작성하는 것이 가능합니다.

**Comment by disjukr** [comment]
@redcamel 음.. 저도 이 라이브러리를 사용해보고 싶은데 이 부분이 걸려서요.. 혹시 제가 위에 작성한대로 구현한다음 PR을 올려봐도 괜찮을까요?

**Comment by redcamel** [comment]
@disjukr 당분간은 이기조는 아마도 유지될겁니다...... 왜냐하면.. 현상을 직시해보면...아무런 문제가 없는 상태거든요...^^ 반대로 종찬군에게 묻고싶은건... 모듈화가 안되어있어서 이걸 못쓰겠다는건... 저로선 이해를 할 수 없다정도랄까...

**Comment by disjukr** [comment]
@redcamel 음.. 제가 보기에는 전역 이름공간을 크게 차지하는 것 자체가 이미 문제라고 생각돼요.

어떤 이름이 어디에서 선언되었는지 파악하기 힘들기 때문에 코드를 읽는데도 시간이 오래 걸리게 되고요.

라이브러리 작성자 입장이랑 라이브러리 사용자 입장은 다르니까요.

**Comment by hikaMaeng** [comment]
음 코드를 컴파일 하는  과정을 안가져 가는 상태니까..
컴파일을 기본으로 하는 환경에 이미 익숙해져버리면 잘 이해가 안되겠지만 ^^;

**Comment by redcamel** [comment]
@disjukr 왜 빌드를 먼가 수정할떄마다 한다고 생각하는거지?
빌드는 최종 반영할떄나 하는정도가 전제임...
watch걸어놓고 빌드하는 상황자체를 이미 기본이라고 생각하고있는거라면 더더욱이...^^ 방향이 조금 다른거고...
그리고 연구 개발시에는...짜피 추가 파일들만 가거나...경로 풀어서 개발하는정도니..
(내가 지금 병합파일들로만 예제를 보여주고있는것도 한몪한듯한데...)

**Comment by redcamel** [comment]
@disjukr 종찬아~~ ^^ 여기까지만^^
의도는충분히알았다고이미이야기한것같아
딱히서로소모적인투자는더이상안해도될듯

**Comment by disjukr** [comment]
좀 생각해봤는데 기존의 워크플로우를(어떤 방식이건) 건드리지 않고도 해결할 수 있을 것 같습니다.

`src` 폴더의 내용은 그대로 두고, `src` 폴더의 내용을 es2015 module으로 변환해주는 스크립트를 작성해서 `lib` 폴더로 떨구게 하면 어떨까 싶은데요,

의존성 추적은 `src` 디렉토리 이하 모듈들의 이름이 각 소스코드 안쪽에 보이면 `import`로 간주할 수 있을 것 같고요.
`gl-matrix`가 벤더링 돼있는게 좀 걸리는데 이 부분만 약간 특수처리를 해주면 될 것 같습니다.

`lib` 폴더는 저장소에 트래킹하지 않고(`.gitignore`), `package.json`의 `prepublishOnly` 스크립트에서 `lib` 폴더로 구워서 npm에 올리도록 하면 기존 저장소의 내용을 크게 건드리지 않고도 (npm publish할 때만 돌아가는 빌드스크립트만 추가) 현대 js 라이브러리의 모양새를 갖추게 할 수 있을 것 같습니다.

이렇게 만들어놓으면 module 방식으로 사용하고 싶은 프로젝트에서는 `npm install redgl2`후,
프로젝트 소스코드에서 `import RedGL from 'redgl2/lib/RedGL';`하여 사용하면 됩니다.

나머지는 기존과 동일합니다.
