### ISSUE TITLE
Orthogonal 모드시 Text 객체를 따로 가져갈건지 결정해야함

### ISSUE THREAD

**Issue by redcamel** [redcamel/RedGL2#408]
Orthogonal 모드시 Text 객체를 따로 가져갈건지 결정해야함

**Comment by hikaMaeng** [comment]
따로 가져가.

첫번째로는 데코레이션 문제.
결국 html태그까지는 아니라도 안드로이드의 spannable 수준까지는 지원되어야 실무에서 쓸만함.
https://developer.android.com/reference/android/text/SpannableString
이쪽 개념에서는 하나의 문자열을 만들 때 스패너블스트링을 조합해서 만드는데
https://developer.android.com/reference/android/text/SpannableStringBuilder
이렇게 빌더로..

쉽게 설명하자면

builder.addPlain("안녕").addLink("선기", "url...").addPlain("야!, ").addColor("수고", "#aaa").addPlain("가 많다").build()

요론 감각이라고 생각하면 된다. 태그까지는 아니라도 이 정도가 지원 안되면 결국 좌표따서 직접 일일히 텍스트 객체를 따로 만들 수 밖에 없어서 괴로움. 

두번째로는 위치와 선택의 문제
예를들어 text객체를 하나 만들었다고 생각하면 이 넘을 좌표에 맞춰 실제로 렌더링 한 건 엔진이니까 오직 엔진만 정확한 커서나 텍스트의 위치를 알 수 있당.

따라서 엔진은 특정 텍스트의 위치를 계산해서 나에게 알려줄 책임이 있지.

const a = new Text("안녕\n선기야") 

라는 상황이면

const {x, y} = a.getTextPosition(1); //두번째 글자(녕)의 좌측상단 위치
const {x, y} = a.getTextPosition(4); //네번째 글자(선)의 좌측상단 위치

이런 것이 제공되어서 내가 위치 기반으로 화면에 뭘 할 수 있어야 하고

const y = a.getLineY(1); //두번째줄 y위치

이런 것도 제공되어야하고

const startX = a.getLineStart(2); //세번째줄 좌측 좌표
const endX = a.getLineEnd(2); //세번째줄 우측끝 좌표

이것도 필요함. 마지막으로 셀렉션 제공 되어야 함.

const {sx, sy, ex, ey, startLine, endLine} = a.getSelection(3, 6);
const select = a.getSelection(3, 6);
select.background('#a00')
select.copy()
select.remove()
select.insertBefore("test")
select.insertAfter("test")
select.replace("test")

화이팅! 형님이 오픈이후라 좀 힘써봤당 ㅎㅎ

**Comment by redcamel** [comment]
@hikaMaeng 편의성은 이제부터 잡아가면될것 같고..
현재는 HTML 태그까지는 기존에도 잘 지원하고있습니다...
- [3d모드 확이](http://localhost:63342/RedGL2/example/text/RedText.html)
- [2d모드 확인](http://localhost:63342/RedGL2/example/text/RedCamera_ortho_text.html)

카메라 오쏘 모드시 px단위 처리로 렌더링 되도록 1차 변경되었습니다. 

위에 주신 아이디어 부분도 따로 실험 해보는 방향으로..

**Comment by hikaMaeng** [comment]
응 주어진 데이터가 그냥 그림으로 렌더링되는 것과 동적 프로그래밍 모델을 제공하는 것의 차이는 크니까.

지금은 렌더링해서 그림만 그려지는거지 텍스트에디터같은걸 만들 수 없잖아. 사실 저 정도만 지원되면 html전체를 다 버리고 이걸로만 렌더링할 수 있을지도 몰라.

**Comment by redcamel** [comment]
@hikaMaeng 오늘 잠깐 어떻게 접근해야할까 고민을 좀 해봤습니다.
완전 오리지날 데이터를 정의 하는건... 시간이 아무래도 걸릴것같고..
dom selection기반의 캐롯 접근으로 span태그와 섞어서 1차 구현해볼생각...

**Comment by redcamel** [comment]
향후 재오픈
