### ISSUE TITLE
add function of Morph Primitives parsing.

### ISSUE THREAD

**Issue by redcamel** [redcamel/RedGL2#425]
add function of Morph Primitives parsing.

**Comment by redcamel** [comment]
처리완료

**Comment by redcamel** [comment]
@cx20 Morph Primitives Test [link](https://redcamel.github.io/RedGL2/example/loader/gltf/RedGLTFLoader_morph.html?idx=41)

**Comment by cx20** [comment]
I updated the status of [gltf-test](https://github.com/cx20/gltf-test#feature-test-models).
