### ISSUE TITLE
Loading glTF file fails because the request header is incorrect

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#429]
I tried to display the [glTF file](https://github.com/KhronosGroup/glTF-WebGL-PBR/blob/master/models/Triangle/glTF/Triangle.gltf) in github from [jsdo.it](http://jsdo.it/cx20/6gc2).
However, an error occurred in the console and could not be loaded.

[RedGL + Triangle.gltf result:](http://jsdo.it/cx20/6gc2)
```
Access to XMLHttpRequest at 'https://cdn.rawgit.com/KhronosGroup/glTF-WebGL-PBR/817404a4/models/Triangle/glTF/Triangle.gltf' 
from origin 'http://jsrun.it' has been blocked 
by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.
```
I do not know the details, but I think that it may be caused by the incorrect request header of `XMLHttpRequest`.
I commented out the following parts of the library and confirmed that it can be loaded.
```javascript
var fileLoader = function (src, type, onLoader, onError) {
    var request = new XMLHttpRequest();
    request.open("GET", src, true);
    //request.setRequestHeader("Content-Type", (type ? type : "application/xml; ") + 'charset=UTF-8') // Commented out
    request.onreadystatechange = function (e) {
        if (request.readyState == 4 && request.status === 200) {
            console.log(request)
            onLoader(request)
        } else {
            onError(request, e)
        }
    }
    request.send();
}
```

**Comment by redcamel** [comment]
@cx20 Thank you for your advice to this library. and fixed this problem. and I'll check all the issues involved.
