### ISSUE TITLE
The orientation of the balloon is incorrect

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#440]
I tried to display the bear's model that was in sketchfab in RedGL.js.
https://sketchfab.com/models/f2f13a8630004b1c82730d8b9ffa0e1f

However, Bear's model is not displayed in the correct orientation.

[RedGL + Bear On Balloons model result:](http://jsdo.it/cx20/8ZrJ)
http://jsdo.it/cx20/8ZrJ
![image](https://user-images.githubusercontent.com/1833979/51179881-21dcda00-190a-11e9-82f8-26722e4eb7b0.png)

[three.js + Bear On Baloons model result:](http://jsdo.it/cx20/6MMO)
http://jsdo.it/cx20/6MMO
![image](https://user-images.githubusercontent.com/1833979/51179965-5d77a400-190a-11e9-96f0-68d1eb5c303f.png)

**Comment by redcamel** [comment]
@cx20 resolved this issue!
test at this [link](http://jsdo.it/webseon/2Y6c).

**Comment by cx20** [comment]
I confirmed that the balloon is correctly displayed by the latest version of RedGL.

[RedGL + Bear On Balloons model result:](http://jsdo.it/cx20/CmcS)
![image](https://user-images.githubusercontent.com/1833979/51248178-b3178380-19d2-11e9-911b-9275d1a68b2f.png)

**Comment by redcamel** [comment]
@cx20 
あなたイジュンテストページのhttps://rawcdn.githack.com/cx20/gltf-test/master/libs/redgl2/20190116/RedGL.jsを見ると、
まだ
/*@preserve
*/
ソースが存在しません。
何かrawcdn.githack.comに上げると、自動的に注釈を削除するとかそんなでしょうか？
