### ISSUE TITLE
project_polly.gltf is not displayed

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#441]
Project "Polly" is a model created to introduce all the new features of glTF 2.0.
https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly

However, RedGL does not seem to be able to display Polly yet.
[RedGL + project_polly.gltf result:](http://jsdo.it/cx20/ImHb)
http://jsdo.it/cx20/ImHb
```
RedGL.js:11963 
Uncaught TypeError: Cannot set property 'geometry' of undefined
    at RedGL.js:11963
    at Array.forEach (<anonymous>)
    at parseSkin (RedGL.js:11959)
    at RedGL.js:12028
    at Array.forEach (<anonymous>)
    at RedGL.js:12016
    at RedGL.js:12059
    at Array.forEach (<anonymous>)
    at RedGL.js:12058
    at tick (RedGL.js:11890)
```

Below is the display result of Three.js and GLTFLoader.
[Three.js + project_polly.gltf result:](http://jsdo.it/cx20/qugw)
http://jsdo.it/cx20/qugw
![image](https://user-images.githubusercontent.com/1833979/51180311-7d5b9780-190b-11e9-9f62-64aa3a730763.png)

**Comment by redcamel** [comment]
@cx20 オホーツク....できるだけ早くチェックしてみましょう。
基本スペックはほとんど解析していると思いましたがブジョクハンゲかですね。

**Comment by hikaMaeng** [comment]
오 선기야 국제 프로젝트되었다

**Comment by redcamel** [comment]
@cx20 
Should be okay now ^^
you can test at this [link](https://redcamel.github.io/RedGL2/example/loader/gltf/RedGLTFLoader_polly.html?idx=45)

**Comment by cx20** [comment]
I confirmed that Polly is displayed by the latest version of RedGL.
[RedGL + project_polly.gltf result:](http://jsdo.it/cx20/yf2v)
![image](https://user-images.githubusercontent.com/1833979/51247978-0a692400-19d2-11e9-8505-cd01c7430c0b.png)
