### ISSUE TITLE
The glTF model of T-Rex is not animated

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#448]
I tried to display the T-Rex model. However, the model is not animated.

[RedGL + T-Rex model result:](http://jsdo.it/cx20/kppQ)
```
RedGL.js:11969 
Uncaught TypeError: Cannot set property 'geometry' of undefined
    at RedGL.js:11969
    at Array.forEach (<anonymous>)
    at parseSkin (RedGL.js:11965)
    at RedGL.js:12036
```

[three.js + T-Rex model result](http://jsdo.it/cx20/aq1x)
![image](https://user-images.githubusercontent.com/1833979/51255626-fc71ce00-19e6-11e9-8f8d-5a028da59f06.png)

**Comment by redcamel** [comment]
@cx20 This problem is the same as the problem of #441.
I fixed this problem more powerfully.

**Comment by redcamel** [comment]
@cx20 test [here](http://jsdo.it/webseon/4gLy).

**Comment by cx20** [comment]
@redcamel Thank you for fixing. But, I think that the way the tail is swung is incorrect.
![image](https://user-images.githubusercontent.com/1833979/51259830-4ad79a80-19f0-11e9-9073-316ff8658b6c.png)

**Comment by redcamel** [comment]
@cx20 
This is a limitation on the maximum number of joints.
currently branching by mobile, browser state. will be fix to use more joints soon.
![image](https://user-images.githubusercontent.com/820587/51294821-041d8b00-1a58-11e9-8350-925459d47b61.png)

**Comment by redcamel** [comment]
@cx20 fixed it. test [here](http://jsdo.it/webseon/4gLy).
current joint limitation.
desktop : 256
mobile : 64
ie11 : 50
iphone, ipad : 8
