### ISSUE TITLE
OES_element_index_uint extension not supported

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#457]
I tried to display a model with many vertices.
However, it seems that it is displayed only halfway.
[RedGL + Kaendoki.glb result:](http://jsdo.it/cx20/4MRs)
![image](https://user-images.githubusercontent.com/1833979/51309589-20d1b700-1a88-11e9-87a0-68d3260c1d09.png)

I think that it is probably caused by not supporting the `OES_element_index_uint extension`.

[three.js + Kaendoki.glb result:](http://jsdo.it/cx20/gtTA)
![image](https://user-images.githubusercontent.com/1833979/51309700-570f3680-1a88-11e9-8fc4-6223833a21af.png)

**Comment by redcamel** [comment]
@cx20 これgltf解析時点で拡張をするかどうかを判別、適用しない問題ですね。処理します。

**Comment by redcamel** [comment]
@cx20 Resolved this issue. test at this [link](http://jsdo.it/webseon/KiOx)

**Comment by cx20** [comment]
I confirmed that all geometries are displayed in the latest version of RedGL.
[RedGL + Kaendoki.glb result:](http://jsdo.it/cx20/sS76)
![image](https://user-images.githubusercontent.com/1833979/51386085-9448f680-1b64-11e9-8a9f-d3525b464f8b.png)
