### ISSUE TITLE
add parsing for GLTF doubleSide

### ISSUE THREAD

**Issue by redcamel** [redcamel/RedGL2#470]
add parsing for GLTF doubleSide
![image](https://user-images.githubusercontent.com/820587/51422702-6613f700-1bf6-11e9-93ab-6f810baa388e.png)

**Comment by redcamel** [comment]
@cx20 resolved. gltf doubleside  - test [link](http://jsdo.it/webseon/8V0i)

**Comment by cx20** [comment]
I confirmed that the double-sided test passes with the latest version of RedGL.
[RedGL + TextureSettingsTest.gltf result:](http://jsdo.it/cx20/4ira)
![image](https://user-images.githubusercontent.com/1833979/51427150-6f718380-1c37-11e9-9076-de84137be4c5.png)
