### ISSUE TITLE
Rocks and trees model does not display properly

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#488]
I tried to display the glTF sample model below in RedGL.
https://ft-lab.github.io/gltf.html

However, in the library before a while, the Rocks and trees model could be displayed, but it seems that it is not displayed correctly in the latest version.

[RedGL 2018.01.16 + Rocks and trees model result:](http://jsdo.it/cx20/mXMr)
![image](https://user-images.githubusercontent.com/1833979/51785424-eb6d4d80-219a-11e9-9117-e22dec19b3e2.png)

[RedGL 2018.01.21 + Rocks and trees model result:](http://jsdo.it/cx20/c3DD)
![image](https://user-images.githubusercontent.com/1833979/51785426-fcb65a00-219a-11e9-9e84-5de1dace256c.png)

**Comment by redcamel** [comment]
@cx20 This is a bug after adding VertexColor parsing function(#456). 
I will check the relationship between VertexColor and BaseColorFactor. Thank you for this report.

**Comment by redcamel** [comment]
@cx20 resolve this issue.
![image](https://user-images.githubusercontent.com/820587/51786377-d5658a00-21a6-11e9-8457-bdf1e4a4a7e2.png)
try this [link](http://jsdo.it/webseon/cDlJ)

**Comment by cx20** [comment]
I confirmed that the problem was solved with the latest version.
[RedGL 2019.01.26 + Rocks and trees model result:](http://jsdo.it/cx20/iLbm)
![image](https://user-images.githubusercontent.com/1833979/51786686-211a3280-21ab-11e9-8ff7-1d8b275a7bbb.png)
