### ISSUE TITLE
add GLTF NormalTangentMirror parser

### ISSUE THREAD

**Issue by redcamel** [redcamel/RedGL2#497]
add GLTF NormalTangentMirror parser

**Comment by redcamel** [comment]
@cx20 NormalTangentMirror parsing problem resolved!! 
check please and test [here](http://jsdo.it/webseon/cRlN)
![image](https://user-images.githubusercontent.com/820587/52202301-7cd27300-28b1-11e9-8c71-d83c032fb9a1.png)

**Comment by cx20** [comment]
@redcamel I confirmed the fix. It looks good.

before:
![image](https://user-images.githubusercontent.com/1833979/52213770-5f160580-28d3-11e9-8fe6-4969b3de1405.png)

after:
![image](https://user-images.githubusercontent.com/1833979/52213813-7d7c0100-28d3-11e9-871b-6e15eb021e51.png)
