### ISSUE TITLE
SimpleTexture.gltf is not displayed correctly

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#526]
I tried to display SimpleTexture.gltf of [glTF Tutorials](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_013_SimpleTexture.md) in RedGL.
However, it seems that it is not displayed correctly.

[RedGL + SimpleTexture.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/86007481701925930c9fe7d132139cbf97ccbe0d/examples/redgl2/index.html?category=tutorialModels&model=SimpleTexture&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52534812-85331e00-2d89-11e9-9984-92a5b1ba2022.png)

[three.js + SimpleTexture.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/86007481701925930c9fe7d132139cbf97ccbe0d/examples/threejs/index.html?category=tutorialModels&model=SimpleTexture&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52534824-a431b000-2d89-11e9-8b50-37680fa186c3.png)

**Comment by redcamel** [comment]
@cx20 haha....

**Comment by redcamel** [comment]
Test results This issue is related to the flipY property.
It may be convenient to switch the accident in a direction that does not use gl.flipY at all.
I'll think about it a little more.
![image](https://user-images.githubusercontent.com/820587/52553378-a269fa00-2e26-11e9-9ff6-f348c3925fc5.png)

**Comment by redcamel** [comment]
@cx20 this issue merged to #527

**Comment by redcamel** [comment]
@cx20 
resolved it. try at this [link](http://jsdo.it/webseon/q10a)

**Comment by cx20** [comment]
@redcamel Thanks! I confirmed that this problem has been solved with the latest version of the library.

[RedGL + SimpleTexture.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/f8c783c9a700f9d44af3bef0999b353e2bf3d850/examples/redgl2/index.html?category=tutorialModels&model=SimpleTexture&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/52656560-fb768280-2f39-11e9-8b9f-3b27efec4fbd.png)
