### ISSUE TITLE
Horse's animation is incorrect

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#549]
I tried to display the [model](https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/Horse.glb) of the horse below in RedGL.
However, it seems that the animation is not displayed properly.

RedGL + Horse.glb result:
http://jsdo.it/cx20/KEQk
![redgl_horse_20190302_002](https://user-images.githubusercontent.com/1833979/53678660-bc03b080-3d05-11e9-9d3c-edf1ef130148.gif)

The following is the expected display result.

three.js + Horse.glb result:
http://jsdo.it/cx20/yPmv
![three_horse_20190302](https://user-images.githubusercontent.com/1833979/53678722-4fd57c80-3d06-11e9-8312-5f8d1248adc8.gif)

**Comment by redcamel** [comment]
@cx20 This problem is probably related to # 509.

**Comment by redcamel** [comment]
@cx20  resolved!
[Test link](https://redcamel.github.io/RedGL2/example/loader/gltf/RedGLTFLoader_Multi_morphTarget.html?idx=45)

**Comment by cx20** [comment]
Thank you for fixing. I think that animation problems are fixed.
However, the color of the horse seems to be a little problem. It seems that half of the body is black.
[RedGL + Horse.glb result:](https://rawcdn.githack.com/cx20/gltf-test/7861ee886805e79e452ef8197ba91c8788887dd5/examples/redgl2/?url=https://rawcdn.githack.com/mrdoob/three.js/fd690f1a6d57d2b12ed471def8608af34fe16b0b/examples/models/gltf/Horse.glb)
![image](https://user-images.githubusercontent.com/1833979/53885723-ca353200-4061-11e9-90f8-b3bfdaa1f07e.png)

The model I used for testing is as follows. I am glad if you reconfirm it.
https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/Horse.glb

**Comment by redcamel** [comment]
@cx20 resolved!!
COLOR_0 attribute was being interpreted only by VEC4.
Fixed by adding parse for VEC3.

![image](https://user-images.githubusercontent.com/820587/53928719-7ad91b00-40ce-11e9-9d99-41e471c02e93.png)

**Comment by cx20** [comment]
I confirmed that this problem has been solved with the latest library.
[RedGL + Horse.glb result:](https://rawcdn.githack.com/cx20/gltf-test/70321765af56a2efafe02dc845a0f4ae51f9adb6/examples/redgl2/index.html?url=https://rawcdn.githack.com/mrdoob/three.js/fd690f1a6d57d2b12ed471def8608af34fe16b0b/examples/models/gltf/Horse.glb&scale=0.01)
![image](https://user-images.githubusercontent.com/1833979/53966718-10a89080-4137-11e9-985d-50c6db24c21a.png)

BTW, It seemed like a setting of the light that half of the body looked black. When I displayed the light from the top to the bottom, I was able to confirm that the color is attached.
![image](https://user-images.githubusercontent.com/1833979/53966881-7006a080-4137-11e9-8edd-07f1ceadf7c8.png)
