### ISSUE TITLE
Fox.gltf is not colored

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#697]
I tried new [model](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Fox) added to [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0).
However, in RedGL [Fox.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Fox)  does not seem to be colored.

[RedGL + Fox.gltf result:](https://cx20.github.io/gltf-test/examples/redgl2/index.html?model=Fox&scale=0.02)
![image](https://user-images.githubusercontent.com/1833979/73484384-8fa85680-43e4-11ea-97a1-81d11b0f6efb.png)

[Three.js + Fox.gltf result:](https://cx20.github.io/gltf-test/examples/threejs/index.html?model=Fox&scale=0.02)
![image](https://user-images.githubusercontent.com/1833979/73484441-ababf800-43e4-11ea-859b-84de26402543.png)

**Comment by redcamel** [comment]
@cx20 
確認が遅れました。
確認の結果、この問題はNORMAL情報がGLTFに存在しない場合は、自動生成をする必要がある問題でした。すぐに処理する予定です。

**Comment by redcamel** [comment]
@cx20 resolved.
![image](https://user-images.githubusercontent.com/820587/73704942-ed67d600-4737-11ea-9196-4d8bf7448d63.png)
resolved. you can play at this [link](https://redcamel.github.io/RedGL2/rnd/gltfNewModel/RedGLTFLoader_newModel)

**Comment by cx20** [comment]
Thanks. I confirmed that this problem has been solved in the latest version of RedGL.
[RedGL + Fox.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/841572a06e64c5ad984a909fa5ca44e990f95e40/examples/redgl2/index.html?category=sampleModels&model=Fox&scale=0.02&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/73743329-9f7fbc00-4791-11ea-837c-a4a68a8646f3.png)
