### ISSUE TITLE
How to apply IBL to glTF?

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#700]
I tried displaying `BoomBox.gltf` using `RedGL`.
I looked at applying Cubemaps and IBL using RedGL, but it didn't work.

[Babylon.js + BoomBox.gltf result:](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=BoomBox&scale=100&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/76757259-a35c2080-67ca-11ea-839f-12b8c7d0c862.png)

[RedGL.js + BoomBox.gltf result:](https://cx20.github.io/gltf-test/examples/redgl2/index.html?category=tutorialModels&model=BoomBox&scale=100&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/76757298-b2db6980-67ca-11ea-98e7-cbe5b04f7b3c.png)

I think it's probably wrong, but I didn't know how to set it up correctly. I'm glad if you get some advice.
https://github.com/cx20/gltf-test/blob/master/examples/redgl2/index.js

**Comment by redcamel** [comment]
@cx20 一度問題を確認しました。
少しの事前調査後すぐに修正いたします。
