### ISSUE TITLE
How to switch animation of Fox.gltf model

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#701]
I tried to display [Fox.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Fox) using RedGL.
Fox.gltf contains three animations (`Survey`, `Walk`, and `Run`).
However, I did not know how to switch it.

[RedGL + Fox.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/c36cd384f2ac0c26b29baed255d47694bcc2ff9d/examples/redgl2/index.html?category=sampleModels&model=Fox&scale=0.02&type=glTF)
By default, the `Survey` animation is played.
![image](https://user-images.githubusercontent.com/1833979/79058187-a0f3c600-7ca5-11ea-8c41-acd2fbbf2542.png)

I want to play the `Run` animation, but I don't know how.
I'm glad if you get some advice.

**Comment by redcamel** [comment]
@cx20 
parsingResult内部のanimations配列を利用してください切り替えは可能です。
```javascript
RedGLTFLoader(
    this, assetPath + 'glTF/basic/AnimatedMorphCube/glTF/',
    'AnimatedMorphCube.gltf', 
    function (v) {
        console.log(v.parsingResult) // check this! 
        // v.stopAnimation() 
 	// v.playAnimation(v.parsingResult.animations[0])
	tScene.addChild(v['resultMesh'])
    }
);
```

**Comment by cx20** [comment]
Hmm, I tried to select the `Run` animation in `Fox.gltf` but it didn't seem to switch.

https://github.com/cx20/gltf-test/blob/master/examples/redgl2/index.js#L89-L90
```javascript
RedGLTFLoader(
    this, // redGL
    base, // assetRootPath
    file, // fileName
    function (v) { // callBack
        v['resultMesh'].scaleX = scale;
        v['resultMesh'].scaleY = scale;
        v['resultMesh'].scaleZ = scale;
        
        if (modelInfo.name == "Fox") {
            v.stopAnimation();
            v.playAnimation(v.parsingResult.animations[2]);  // "Run"
        }
        
        tScene.addChild(v['resultMesh']);
    },

```

[RedGL + Fox.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/498b778ceee19ee9c782f2ae0ebba28d91cd8999/examples/redgl2/index.html?category=sampleModels&model=Fox&scale=0.02&type=glTF)

**Comment by redcamel** [comment]
@cx20 
ロードした後プレイ管理側のバグを発見した。
いつがから発生したとみられ、今日夜遅くでも修正しておきました。いつも良いフィードバックありがとうございます。

**Comment by cx20** [comment]
@redcamel 

I'm trying the libraries in the release folder but the situation doesn't seem to change. The modified date of the file is 2020.03.18. Isn't it the latest version?
https://github.com/redcamel/RedGL2/blob/dev/release/RedGL.js

Do I need to build the latest version?
