### ISSUE TITLE
particle emitter tilt animation

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGL2#702]
```
this['_interleaveData'][tIndex + 4] = tInfo['tint'][0];
this['_interleaveData'][tIndex + 5] = tInfo['tint'][1];
this['_interleaveData'][tIndex + 6] = tInfo['tint'][2];
```
아니 왜 얘들만 particle값을 안쓰고 tInfo값을 씀?
얘들도 파티클 시작시점에 tInfo값을 복사해오고 갸로 작동하게 바꿔야함.
tInfo에 의존하다보니 개별 파티클이 생성시점의 tilt가 유지안됨.

**Comment by hikaMaeng** [comment]
이거 언제 만들어줌 ^^
게다가 이징함수 외에 결국 랜덤이다 뿐이지 시작에서 끝이 다 선형으로만 움직임.
패스애니메이션이 들어왔으면 좋겠음.
```js
particle: {
   movementX: {
      start: 0, end: 100, ease: RedParticleEmitter.QuadInOut, 
      path:"M20,30S30,50,60,70"
   },
},
```
대충 이런식이되려나? 그러고보니 3차원 패스 지원하고 있던가?
문서상에서는 line, curve, path, point 가 없던데..

**Comment by hikaMaeng** [comment]
빨리 고쳐줘~

**Comment by redcamel** [comment]
아.....이걸해야되는군 -_-;;;;
