### ISSUE TITLE
RedGL canvas size

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGL2#703]
나 초기화 시점에 
```
this.setSize(500, 500);
```
한 뒤에 renderer사용했는데 renderer가 전체화면으로 바꿔버림.
setSize했으면 이 크기가 유지되어야하는거 아닌감?

**Comment by redcamel** [comment]
@hikaMaeng 일단 이놈은 문제가 될일은 아마 없을것 같은데 내일 소스한번 알려주세요

**Comment by hikaMaeng** [comment]
해결했음. "500" 이라고 쓴게 문제였음.
