### ISSUE TITLE
Single World, multi Scene render or multi world render

### ISSUE THREAD

**Issue by hikaMaeng** [redcamel/RedGL2#704]
한 캔버스에서 다른 scene으로 하나에서는 3d돌리고 다른 곳에서는 그래프를 그릴려고 하는데
VIEW은 짜피 같은걸 카메라만 바꿔서 보여주는거고,
이 경우 
```
this['world1'] = world1;
this['world2'] = world2;
this['world3'] = world3;
```
이렇게 하는건가, 아니면 
```
world.addView(RedView(this, scene1, ctrl1))
world.addView(RedView(this, scene2, ctrl2))
world.addView(RedView(this, scene3, ctrl3))
```
이렇게 하는건가.

**Comment by redcamel** [comment]
@hikaMaeng 후자쪽이요

https://redcamel.github.io/RedGL2/example/etc/RedView.html?idx=2
요놈이 예제긴합니다.

**Comment by hikaMaeng** [comment]
아니 이건 같은 씬을 가리키고 있어서 씬이 다를 때 괜찮은지 잘 모르겠더라구
