### ISSUE TITLE
Fails to display if only doubleSided is used in the material

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#706]
I tried displaying the new SimpleSkin model in RedGL.
However, an error occurs and is not displayed.

[RedGL + new SimpleSkin.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/8511bb1d21be616d811393093d6ec957914dad8a/examples/redgl2/index.html?category=tutorialModels&model=SimpleSkin&scale=1&type=glTF)
```javascript
RedGL.min.js:1025 
Uncaught TypeError: Cannot use 'in' operator to search for 'baseColorTexture' in undefined
```

Probably due to the lack of `pbrMetallicRoughness` in this model's `material`, but this is _not_ a required item.
```json
  "materials" : [ {
    "doubleSided" : true
  } ],
```

**Comment by cx20** [comment]
BTW, In the latest version of [SimpleSkin.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SimpleSkin), it seems that the `materials` has been removed to simplify the sample model.

Use the model below to test this issue.
[SimpleSkin.gltf (with doubleSided)](https://rawcdn.githack.com/cx20/gltf-test/8511bb1d21be616d811393093d6ec957914dad8a/tutorialModels/SimpleSkin/glTF/SimpleSkin.gltf)

**Comment by redcamel** [comment]
@cx20 ok... i will check this problem.

**Comment by redcamel** [comment]
@cx20 https://redcamel.github.io/RedGL2/rnd/gltfNewModel/RedGLTFLoader_newModel.html
