### ISSUE TITLE
Undefined error when trying to view TextureEncodingTest.gltf

### ISSUE THREAD

**Issue by cx20** [redcamel/RedGL2#709]
I tried Khronos' new test model [TextureEncodingTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/encoding/2.0/TextureEncodingTest) with RedGL.
However, I get an Undefined error in the console and can't see it

Test model:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/encoding/2.0/TextureEncodingTest

Expected result:
![image](https://user-images.githubusercontent.com/1833979/108509779-06bad080-7301-11eb-8e7c-3e93a524f679.png)

[Current result:](https://cx20.github.io/gltf-test/examples/redgl2/index.html?category=tutorialModels&model=TextureEncodingTest&scale=0.2&type=glTF)
```javascript
RedGL.min.js:1025 
Uncaught TypeError: Cannot use 'in' operator to search for 'magFilter' in undefined
    at v (RedGL.min.js:1025)
    at P (RedGL.min.js:1025)
    at RedGL.min.js:1025
    at Array.forEach (<anonymous>)
    at o (RedGL.min.js:1025)
    at d (RedGL.min.js:1025)
    at RedGL.min.js:1025
    at Array.forEach (<anonymous>)
    at d (RedGL.min.js:1025)
    at s (RedGL.min.js:1025)
```

**Comment by redcamel** [comment]
resolved

**Comment by cx20** [comment]
I have confirmed that the latest version of `RedGL` has resolved the `undefined` error.

It's different from the expected result image, but I think this is another issue.

[RedGL 2021.07.19 + TextureEncodingTest.gltf result:](https://cx20.github.io/gltf-test/examples/redgl2/index.html?category=tutorialModels&model=TextureEncodingTest&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/127872912-ccc28503-983b-44e8-9038-67ec5ac09dbd.png)
